{{--
    Who ran the report, signed by hand.

    Part of the document rather than page furniture: it prints, it exports,
    and it sits after the last summary instead of being pinned to the foot of
    the paper, so a report that ends halfway down a page does not leave a
    signature stranded on a sheet of its own.

    The rule sits well below the name of whoever generated it - a signature is
    written above the printed name, and needs room to be written in.
--}}
<div class="signature-block">
    <table class="signature-table">
        <tr>
            <td class="signature-cell">
                <div class="signature-label">Generated By:</div>
                <div class="signature-space">&nbsp;</div>
                <div class="signature-line"></div>
                <div class="signature-name">{{ $generatedBy }}</div>
                <div class="signature-role">Signature over printed name</div>
            </td>
            <td class="signature-spacer">&nbsp;</td>
        </tr>
    </table>
</div>
