<?php

namespace Tests\Feature;

use App\Console\Commands\RepairUnusablePasswords;
use App\Mail\OtpCodeMail;
use App\Models\PendingRegistration;
use App\Models\User;
use App\Services\ProfileService;
use App\Services\SystemContentService;
use App\Services\UserAccountService;
use App\Support\PasswordPolicy;
use Database\Seeders\SuperAdminSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Testing\TestResponse;
use PHPUnit\Framework\Attributes\DataProvider;
use RuntimeException;
use Tests\TestCase;

/**
 * One password policy, held to by every way a password comes into being.
 *
 * An uppercase letter, a lowercase letter, a number, a special character and
 * at least eight characters - whether the password is chosen at registration,
 * on the forced first-sign-in change, on the profile, through a forgotten
 * password reset, typed by an administrator, generated by the system, or
 * handed to the console repair. Passwords already stored are left alone.
 */
class PasswordPolicyTest extends TestCase
{
    use RefreshDatabase;

    private const STRONG = 'Str0ng#Passw0rd';

    /**
     * Each one misses at least one requirement, with the sentence that says
     * exactly what.
     *
     * @return array<string, array{0: string, 1: string}>
     */
    public static function weakPasswords(): array
    {
        return [
            'all lower case' => ['password', 'Password must contain at least one uppercase letter, one number and one special character.'],
            'no number or symbol' => ['Password', 'Password must contain at least one number and one special character.'],
            'no upper case or symbol' => ['password1', 'Password must contain at least one uppercase letter and one special character.'],
            'no symbol' => ['Password1', 'Password must contain at least one special character.'],
            'no number' => ['Password!', 'Password must contain at least one number.'],
            'no upper case or number' => ['password!', 'Password must contain at least one uppercase letter and one number.'],
            'no lower case' => ['PASSWORD1!', 'Password must contain at least one lowercase letter.'],
            'too short' => ['Pa1!', 'Password must be at least 8 characters long.'],
            'a space is not a symbol' => ['Pass word1', 'Password must contain at least one special character.'],
            'short and missing everything' => ['short', 'Password must be at least 8 characters long and contain at least one uppercase letter, one number and one special character.'],
        ];
    }

    /**
     * @return array<string, array{0: string}>
     */
    public static function strongPasswords(): array
    {
        return [
            'mixed with a bang' => ['Password1!'],
            'symbol in the middle' => ['Str0ng#Pass'],
            'dashes as symbols' => ['my-Secret-2026'],
            'exactly eight' => ['X9@yzabc'],
            'caret and ampersand' => ['a^B&c*D1'],
            'with spaces too' => ['Correct Horse 9!'],
            'other scripts alongside' => ['Ünïcode-Pass9'],
        ];
    }

    // ------------------------------------------------------------------
    // The policy itself
    // ------------------------------------------------------------------

    #[DataProvider('weakPasswords')]
    public function test_a_weak_password_is_refused_with_everything_it_lacks(string $password, string $message): void
    {
        $this->assertFalse(PasswordPolicy::isSatisfiedBy($password));
        $this->assertSame($message, PasswordPolicy::failureMessage($password));
    }

    #[DataProvider('strongPasswords')]
    public function test_a_password_with_every_kind_of_character_passes(string $password): void
    {
        $this->assertTrue(PasswordPolicy::isSatisfiedBy($password));
        $this->assertNull(PasswordPolicy::failureMessage($password));
    }

    public function test_the_checklist_is_drawn_from_the_same_patterns_the_server_tests(): void
    {
        $checklist = collect(PasswordPolicy::checklist())->keyBy('key');

        $this->assertSame(['length', 'uppercase', 'lowercase', 'number', 'symbol'], $checklist->keys()->all());
        $this->assertSame(PasswordPolicy::MIN_LENGTH, $checklist['length']['min_length']);

        foreach (PasswordPolicy::CHARACTER_REQUIREMENTS as $key => $requirement) {
            $this->assertSame($requirement['pattern'], $checklist[$key]['pattern']);
        }
    }

    // ------------------------------------------------------------------
    // Registration
    // ------------------------------------------------------------------

    #[DataProvider('weakPasswords')]
    public function test_registration_refuses_a_weak_password_even_when_confirmed(string $password, string $message): void
    {
        Mail::fake();

        $this->register($password)->assertSessionHasErrors(['password' => $message]);

        $this->assertDatabaseCount('tbl_pending_registrations', 0);
        Mail::assertNothingSent();
    }

    #[DataProvider('strongPasswords')]
    public function test_registration_accepts_a_strong_password(string $password): void
    {
        Mail::fake();

        $this->register($password)->assertRedirect(route('auth.verify'));

        $pending = PendingRegistration::where('email', 'jose@example.test')->firstOrFail();
        $this->assertTrue(Hash::check($password, $pending->password));
    }

    public function test_a_strong_password_still_has_to_match_its_confirmation(): void
    {
        $this->register(self::STRONG, 'Str0ng#Different')
            ->assertSessionHasErrors(['password' => 'The two passwords do not match.']);

        $this->assertDatabaseCount('tbl_pending_registrations', 0);
    }

    // ------------------------------------------------------------------
    // Forced first-sign-in change (temporary password replacement)
    // ------------------------------------------------------------------

    #[DataProvider('weakPasswords')]
    public function test_a_temporary_password_cannot_be_replaced_with_a_weak_one(string $password, string $message): void
    {
        $user = $this->account('admin', ['must_change_password' => true]);

        $this->actingAs($user)
            ->post(route('auth.password.update'), [
                'current_password' => 'Temp-pass-1',
                'password' => $password,
                'password_confirmation' => $password,
            ])
            ->assertSessionHasErrors(['password' => $message]);

        $user->refresh();
        $this->assertTrue(Hash::check('Temp-pass-1', $user->password));
        $this->assertTrue((bool) $user->must_change_password);
    }

    public function test_a_temporary_password_is_replaced_with_a_strong_one(): void
    {
        $user = $this->account('admin', ['must_change_password' => true]);

        $this->actingAs($user)
            ->post(route('auth.password.update'), [
                'current_password' => 'Temp-pass-1',
                'password' => self::STRONG,
                'password_confirmation' => self::STRONG,
            ])
            ->assertRedirect(route('super-admin.dashboard'));

        $user->refresh();
        $this->assertTrue(Hash::check(self::STRONG, $user->password));
        $this->assertFalse((bool) $user->must_change_password);
    }

    // ------------------------------------------------------------------
    // Profile password change
    // ------------------------------------------------------------------

    #[DataProvider('weakPasswords')]
    public function test_the_profile_refuses_a_weak_new_password(string $password, string $message): void
    {
        $user = $this->account('technician');

        $this->actingAs($user)
            ->put(route('profile.password'), [
                'current_password' => 'Temp-pass-1',
                'password' => $password,
                'password_confirmation' => $password,
            ])
            ->assertSessionHasErrors(['password' => $message], null, 'password');

        $this->assertTrue(Hash::check('Temp-pass-1', $user->refresh()->password));
    }

    public function test_the_profile_accepts_a_strong_new_password(): void
    {
        $user = $this->account('technician');

        $this->actingAs($user)
            ->put(route('profile.password'), [
                'current_password' => 'Temp-pass-1',
                'password' => self::STRONG,
                'password_confirmation' => self::STRONG,
            ])
            ->assertSessionHas('success', 'Password updated.');

        $this->assertTrue(Hash::check(self::STRONG, $user->refresh()->password));
    }

    // ------------------------------------------------------------------
    // Forgotten password reset
    // ------------------------------------------------------------------

    #[DataProvider('weakPasswords')]
    public function test_a_forgotten_password_cannot_be_reset_to_a_weak_one(string $password, string $message): void
    {
        $user = $this->account('client');
        $this->verifyResetCodeFor($user);

        $this->post(route('auth.password.store'), [
            'password' => $password,
            'password_confirmation' => $password,
        ])->assertSessionHasErrors(['password' => $message]);

        $this->assertTrue(Hash::check('Temp-pass-1', $user->refresh()->password));
    }

    public function test_a_forgotten_password_is_reset_to_a_strong_one(): void
    {
        $user = $this->account('client');
        $this->verifyResetCodeFor($user);

        $this->post(route('auth.password.store'), [
            'password' => self::STRONG,
            'password_confirmation' => self::STRONG,
        ])->assertRedirect(route('auth.login'));

        $this->assertTrue(Hash::check(self::STRONG, $user->refresh()->password));
    }

    // ------------------------------------------------------------------
    // Accounts opened by an administrator
    // ------------------------------------------------------------------

    #[DataProvider('weakPasswords')]
    public function test_an_administrator_cannot_type_a_weak_password_for_an_employee(string $password, string $message): void
    {
        $this->actingAsSuperAdmin();

        $this->postJson(route('super-admin.configuration.users.employees.store'), [
            'first_name' => 'Ana',
            'last_name' => 'Mendoza',
            'contact_number' => '09175551234',
            'birthdate' => '1990-05-04',
            'email' => 'ana@example.test',
            'role' => 'admin',
            'password' => $password,
        ])->assertStatus(422)->assertJsonPath('error', $message);

        $this->assertNull(User::where('email', 'ana@example.test')->first());
    }

    #[DataProvider('weakPasswords')]
    public function test_an_administrator_cannot_type_a_weak_password_for_a_client(string $password, string $message): void
    {
        $this->actingAsSuperAdmin();

        $this->postJson(route('super-admin.configuration.users.clients.store'), [
            'full_name' => 'Jose Garcia',
            'contact_number' => '09175551234',
            'birthdate' => '1988-11-20',
            'email' => 'jose@example.test',
            'password' => $password,
        ])->assertStatus(422)->assertJsonPath('error', $message);

        $this->assertNull(User::where('email', 'jose@example.test')->first());
    }

    public function test_a_strong_typed_password_is_used_and_still_has_to_be_replaced(): void
    {
        $this->actingAsSuperAdmin();

        $this->postJson(route('super-admin.configuration.users.employees.store'), [
            'first_name' => 'Ana',
            'last_name' => 'Mendoza',
            'contact_number' => '09175551234',
            'birthdate' => '1990-05-04',
            'email' => 'ana@example.test',
            'role' => 'admin',
            'password' => self::STRONG,
        ])->assertCreated()->assertJsonPath('password', self::STRONG);

        $user = User::where('email', 'ana@example.test')->firstOrFail();
        $this->assertTrue(Hash::check(self::STRONG, $user->password));
        $this->assertTrue((bool) $user->must_change_password);
    }

    public function test_a_blank_password_is_replaced_by_a_generated_one_that_meets_the_policy(): void
    {
        $this->actingAsSuperAdmin();

        $response = $this->postJson(route('super-admin.configuration.users.clients.store'), [
            'full_name' => 'Jose Garcia',
            'contact_number' => '09175551234',
            'birthdate' => '1988-11-20',
            'email' => 'jose@example.test',
            'password' => '',
        ])->assertCreated();

        $this->assertTrue(PasswordPolicy::isSatisfiedBy($response->json('password')));
    }

    // ------------------------------------------------------------------
    // Administrator resets and generated passwords
    // ------------------------------------------------------------------

    public function test_every_generated_password_meets_the_policy(): void
    {
        $accounts = app(UserAccountService::class);

        foreach (range(1, 200) as $attempt) {
            $password = $accounts->generateTemporaryPassword();

            $this->assertTrue(
                PasswordPolicy::isSatisfiedBy($password),
                'Generated password failed the policy: '.PasswordPolicy::failureMessage($password)
            );
        }
    }

    /**
     * A Super Admin resetting an Admin, and the Admin then replacing what
     * they were issued: strong on the way out, strong on the way back in.
     */
    public function test_a_super_admin_reset_issues_a_strong_password_that_must_be_replaced_with_another(): void
    {
        $this->actingAsSuperAdmin();
        $admin = $this->account('admin');

        $issued = $this->putJson(route('super-admin.configuration.users.password.reset', $admin))
            ->assertOk()
            ->json('password');

        $admin->refresh();
        $this->assertTrue(PasswordPolicy::isSatisfiedBy($issued));
        $this->assertTrue(Hash::check($issued, $admin->password));
        $this->assertTrue((bool) $admin->must_change_password);

        auth()->logout();

        $this->post(route('auth.login.attempt'), ['email' => $admin->email, 'password' => $issued])
            ->assertRedirect(route('auth.password.change'));

        $this->post(route('auth.password.update'), [
            'current_password' => $issued,
            'password' => 'Password1',
            'password_confirmation' => 'Password1',
        ])->assertSessionHasErrors(['password' => 'Password must contain at least one special character.']);

        $this->assertTrue((bool) $admin->refresh()->must_change_password);

        $this->post(route('auth.password.update'), [
            'current_password' => $issued,
            'password' => self::STRONG,
            'password_confirmation' => self::STRONG,
        ])->assertRedirect(route('super-admin.dashboard'));

        $this->assertFalse((bool) $admin->refresh()->must_change_password);
    }

    public function test_an_admin_reset_of_an_employee_issues_a_strong_password(): void
    {
        $admin = $this->account('admin');
        $technician = $this->account('technician');

        $issued = $this->actingAs($admin)
            ->putJson(route('super-admin.configuration.users.password.reset', $technician))
            ->assertOk()
            ->json('password');

        $this->assertTrue(PasswordPolicy::isSatisfiedBy($issued));
        $this->assertTrue((bool) $technician->refresh()->must_change_password);
    }

    // ------------------------------------------------------------------
    // Paths with no form in front of them
    // ------------------------------------------------------------------

    public function test_the_profile_service_refuses_a_weak_password_from_any_caller(): void
    {
        $user = $this->account('technician');

        try {
            app(ProfileService::class)->updatePassword($user, 'Password1');
            $this->fail('A weak password was accepted.');
        } catch (RuntimeException $exception) {
            $this->assertSame('Password must contain at least one special character.', $exception->getMessage());
        }

        $this->assertTrue(Hash::check('Temp-pass-1', $user->refresh()->password));
    }

    public function test_the_account_service_refuses_a_weak_password_from_any_caller(): void
    {
        $accounts = app(UserAccountService::class);

        $attempts = [
            fn () => $accounts->createEmployee([
                'first_name' => 'Ana', 'last_name' => 'Mendoza', 'contact_number' => '09175551234',
                'birthdate' => '1990-05-04', 'email' => 'ana@example.test', 'role' => 'admin',
                'password' => 'password1',
            ]),
            fn () => $accounts->createClient([
                'full_name' => 'Jose Garcia', 'contact_number' => '09175551234',
                'birthdate' => '1988-11-20', 'email' => 'jose@example.test', 'password' => 'Password!',
            ]),
            fn () => $accounts->startRegistration([
                'full_name' => 'Maria Santos', 'contact_number' => '09175551234',
                'birthdate' => '1988-11-20', 'email' => 'maria@example.test', 'password' => 'PASSWORD1!',
            ]),
            fn () => $accounts->registerClient([
                'full_name' => 'Maria Santos', 'contact_number' => '09175551234',
                'birthdate' => '1988-11-20', 'email' => 'maria@example.test', 'password' => 'password!',
            ]),
        ];

        foreach ($attempts as $attempt) {
            try {
                $attempt();
                $this->fail('A weak password was accepted.');
            } catch (RuntimeException $exception) {
                $this->assertStringStartsWith('Password must', $exception->getMessage());
            }
        }

        $this->assertSame(0, User::count());
        $this->assertDatabaseCount('tbl_pending_registrations', 0);
    }

    public function test_the_repair_command_refuses_a_weak_shared_password_and_changes_nothing(): void
    {
        $broken = $this->account('technician');
        DB::table('users')->where('id', $broken->id)->update(['password' => 'placeholder']);

        $this->artisan('users:repair-passwords', ['--password' => 'password1'])
            ->expectsOutputToContain('Password must contain at least one uppercase letter and one special character.')
            ->assertExitCode(RepairUnusablePasswords::FAILURE);

        $this->assertSame('placeholder', DB::table('users')->where('id', $broken->id)->value('password'));
    }

    public function test_the_super_admin_seeder_refuses_a_weak_password(): void
    {
        $this->withSuperAdminPassword('1234567', function (): void {
            try {
                app(SuperAdminSeeder::class)->run();
                $this->fail('The seeder accepted a weak password.');
            } catch (RuntimeException $exception) {
                $this->assertStringContainsString('SUPER_ADMIN_PASSWORD does not meet the password policy.', $exception->getMessage());
                // The value itself is never repeated back.
                $this->assertStringNotContainsString('1234567', $exception->getMessage());
            }
        });

        $this->assertSame(0, User::count());

        $this->withSuperAdminPassword(self::STRONG, function (): void {
            app(SuperAdminSeeder::class)->run();
        });

        $owner = User::where('role', User::ROLE_SUPER_ADMIN)->firstOrFail();
        $this->assertTrue(Hash::check(self::STRONG, $owner->password));
    }

    // ------------------------------------------------------------------
    // Existing passwords
    // ------------------------------------------------------------------

    /**
     * The policy applies when a password is set, never to one already
     * stored: nobody is locked out or pushed to change by its arrival.
     */
    public function test_an_existing_weak_password_still_signs_in_without_a_forced_change(): void
    {
        $user = $this->account('admin', ['password' => 'password']);

        $this->post(route('auth.login.attempt'), ['email' => $user->email, 'password' => 'password'])
            ->assertRedirect(route('super-admin.dashboard'));

        $this->assertAuthenticatedAs($user);
        $this->assertFalse((bool) $user->refresh()->must_change_password);
    }

    // ------------------------------------------------------------------
    // The checklist on every form
    // ------------------------------------------------------------------

    public function test_every_form_that_sets_a_password_shows_the_requirements(): void
    {
        $this->assertShowsRequirements($this->get(route('auth.register')), 'password');

        $temporary = $this->account('admin', ['must_change_password' => true]);
        $this->assertShowsRequirements($this->actingAs($temporary)->get(route('auth.password.change')), 'password');

        $member = $this->account('technician');
        $this->assertShowsRequirements($this->actingAs($member)->get(route('profile.edit')), 'newPassword');

        $this->actingAsSuperAdmin();
        $this->assertShowsRequirements($this->get(route('super-admin.configuration.index')), 'userTempPassword');

        auth()->logout();
        $client = $this->account('client');
        $this->verifyResetCodeFor($client);
        $this->assertShowsRequirements($this->get(route('auth.password.reset')), 'password');
    }

    // ------------------------------------------------------------------
    // Helpers
    // ------------------------------------------------------------------

    /**
     * @param  array<string, mixed>  $overrides
     */
    private function account(string $role, array $overrides = []): User
    {
        $sequence = User::count() + 1;

        return User::create(array_merge([
            'user_code' => ($role === 'client' ? 'CLI-' : 'EMP-').str_pad((string) (100 + $sequence), 4, '0', STR_PAD_LEFT),
            'name' => 'Test Person',
            'first_name' => 'Test',
            'last_name' => 'Person',
            'email' => 'person'.$sequence.'@example.test',
            'role' => $role,
            'status' => User::STATUS_ACTIVE,
            'email_verified_at' => now(),
            // Accounts the terms gate would otherwise stop at the door.
            'terms_accepted_version' => app(SystemContentService::class)->termsVersion(),
            'terms_accepted_at' => now(),
            'password' => 'Temp-pass-1',
        ], $overrides));
    }

    private function register(string $password, ?string $confirmation = null): TestResponse
    {
        return $this->post(route('auth.register.store'), [
            'full_name' => 'Jose Garcia',
            'email' => 'jose@example.test',
            'contact_number' => '09175551234',
            'birthdate' => '1990-05-04',
            'password' => $password,
            'password_confirmation' => $confirmation ?? $password,
            'terms' => '1',
        ]);
    }

    /**
     * Walk the forgotten-password flow up to the point where a new password
     * is asked for.
     */
    private function verifyResetCodeFor(User $user): void
    {
        Mail::fake();
        config(['mail.default' => 'smtp']);

        $this->post(route('auth.password.email'), ['email' => $user->email]);

        $code = null;
        Mail::assertSent(OtpCodeMail::class, function (OtpCodeMail $mail) use (&$code): bool {
            $code = $mail->code;

            return true;
        });

        $this->post(route('auth.password.verify.store'), ['code' => (string) $code])
            ->assertRedirect(route('auth.password.reset'));
    }

    private function assertShowsRequirements(TestResponse $response, string $inputId): void
    {
        $response->assertOk();
        $response->assertSee('data-password-requirements="'.$inputId.'"', false);
        $response->assertSee('/js/passwordField.js', false);

        foreach (PasswordPolicy::checklist() as $requirement) {
            $response->assertSee($requirement['label']);

            if ($requirement['pattern']) {
                $response->assertSee('data-pattern="'.e($requirement['pattern']).'"', false);
            }
        }
    }

    /**
     * Run with SUPER_ADMIN_PASSWORD set to this value, and put back whatever
     * was there after.
     */
    private function withSuperAdminPassword(string $value, callable $callback): void
    {
        $previous = [$_ENV['SUPER_ADMIN_PASSWORD'] ?? null, $_SERVER['SUPER_ADMIN_PASSWORD'] ?? null, getenv('SUPER_ADMIN_PASSWORD')];

        $_ENV['SUPER_ADMIN_PASSWORD'] = $_SERVER['SUPER_ADMIN_PASSWORD'] = $value;
        putenv('SUPER_ADMIN_PASSWORD='.$value);

        try {
            $callback();
        } finally {
            [$env, $server, $put] = $previous;

            if ($env === null) {
                unset($_ENV['SUPER_ADMIN_PASSWORD']);
            } else {
                $_ENV['SUPER_ADMIN_PASSWORD'] = $env;
            }

            if ($server === null) {
                unset($_SERVER['SUPER_ADMIN_PASSWORD']);
            } else {
                $_SERVER['SUPER_ADMIN_PASSWORD'] = $server;
            }

            putenv($put === false ? 'SUPER_ADMIN_PASSWORD' : 'SUPER_ADMIN_PASSWORD='.$put);
        }
    }
}
