{{--
    The generated report, as a sheet of paper.

    Rendered on the server from the same figures the PDF is built from and
    handed to the Reports page, which drops it into the preview modal. Nothing
    here is dashboard furniture: no cards, no badges, no colour carrying
    meaning - it is a document, and it is styled by
    css/super-admin/report-print.css for the screen and for the printer.

    The whole article is what @media print keeps; everything else on the page
    is hidden, so Print produces the report and nothing around it.
--}}
<article class="report-doc" id="reportDocument">

    {{-- ---------------- Letterhead ---------------- --}}
    <header class="report-doc-head">
        <div class="report-doc-brand">
            @if ($logoData)
                <img src="{{ $logoData }}" alt="" class="report-doc-logo">
            @endif
            <div>
                <div class="report-doc-company">{{ $company['name'] }}</div>
                <div class="report-doc-company-meta">
                    {{ $company['address'] }}<br>
                    {{ $company['system'] }}
                </div>
            </div>
        </div>

        <div class="report-doc-identity">
            <h1 class="report-doc-title">{{ $reportTitle }}</h1>
            <dl class="report-doc-meta">
                <div>
                    <dt>Reporting Period</dt>
                    <dd>
                        {{ $period['label'] }}
                        ({{ $period['start']->format(\App\Support\BusinessTime::DATE) }}
                        &ndash;
                        {{ $period['end']->format(\App\Support\BusinessTime::DATE) }})
                    </dd>
                </div>

                @foreach ($appliedFilters as $filterLabel => $filterValue)
                    <div>
                        <dt>{{ $filterLabel }}</dt>
                        <dd>{{ $filterValue }}</dd>
                    </div>
                @endforeach

                <div>
                    <dt>Generated By</dt>
                    <dd>{{ $generatedBy }}</dd>
                </div>
                <div>
                    <dt>Generated</dt>
                    <dd>{{ \App\Support\BusinessTime::format($generatedAt, \App\Support\BusinessTime::DATE_TIME) }}</dd>
                </div>
            </dl>
        </div>
    </header>

    {{-- ---------------- Body ---------------- --}}
    <div class="report-doc-body">
        @include('super-admin.partials.report-sections', ['report' => $report])
    </div>

    {{-- ---------------- Sign-off ---------------- --}}
    @include('super-admin.partials.report-signature', ['generatedBy' => $generatedBy])

    {{-- The same standing note the PDF carries at the foot of every page.
         A browser writes its own page numbers into the print margin, so the
         document does not try to write them itself. --}}
    <footer class="report-doc-foot">
        <span>{{ $company['name'] }}</span>
        <span>Archived projects are excluded from this report.</span>
    </footer>
</article>
